"""Change user

Revision ID: 4f9cbf4601e0
Revises: 3513b551bb5f
Create Date: 2023-06-04 14:29:29.171614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9cbf4601e0'
down_revision = '3513b551bb5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sa.String(), nullable=False))
    op.drop_column('user', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
