"""Create personal

Revision ID: 89178159b244
Revises: a71d4c06808d
Create Date: 2023-06-04 14:34:54.539948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89178159b244'
down_revision = 'a71d4c06808d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal')
    # ### end Alembic commands ###
